services:
  ollama:
    # container_name: ollama-server-container
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network

  qdrant:
    # container_name: qdrant-container
    image: qdrant/qdrant:v1.15.0
    ports:
      - "6333:6333" # http api
      - "6334:6334" # gRPC api 
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  ollama-data:
  qdrant-data: